// This file is generated

I_death_place_0 = [
"",
"",
"",
"",
"Leicester, Leicestershire, England",
"",
"Horbury, West Yorkshire, England",
"",
"",
"",
"",
"",
"",
"Midgley, Yorkshire, England",
"",
"",
"",
"",
"",
"",
"Cornwall,England",
"Leicestershire, England",
"Bracknell, Berkshire, England",
"",
"",
"Devon, England",
"",
"Crediton, Devon, England",
"",
"",
"",
"",
"",
"",
"Whetstone, Leicestershire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Dover, New Hampshire, USA",
"",
"",
"",
"",
"",
"",
"St Agnes, Cornwall, England",
"",
"",
"",
"",
"",
"",
"Horley, Surrey, England",
"",
"",
"",
"",
"",
"Frome, Somerset, England",
"",
"Exeter, Devon, England",
"Wigan, Greater Manchester, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Ellesmere Port, Cheshire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Auckland, New Zealand",
"",
"",
"",
"Exeter, Devon, England",
"",
"",
"",
"Ontario, Canada",
"Kingston, Ontario, Canada",
"",
"",
"Sheffield, South Yorkshire, England",
"",
"",
"",
"Surrey, England",
"",
"",
"",
"",
"",
"",
"Enfield, Greater London, England",
"Bath, Somerset, England",
"Wandsworth, Greater London, England",
"",
"",
"",
"",
"Wandsworth, Greater London, England",
"Kingston Upon Thames, Greater London, England",
"Bedford Hospital,Bedford,Bedfordshire,England",
"",
"",
"",
"",
"",
"",
"Wandsworth, Greater London, England",
"",
"Northallerton, North Yorkshire, England",
"",
"",
"Haywards Heath, West Sussex, England",
"",
"Anglesey, Wales",
"",
"",
"",
"",
"",
"",
"",
"",
"Crowborough, East Sussex, England",
"Milton Keynes Hospital, Milton Keynes, Buckinghamshire, England",
"",
"",
"Surrey, England",
"",
"",
"",
"",
"",
"",
"",
"",
"St Pancras, London, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Dunmow, Essex, England",
"",
"",
"Saffron Walden, Essex, England",
"Halifax, West Yorkshire, England",
"Great Sampford, Essex, England",
"Suffolk, England",
"Carmarthen,Camarthenshire,Wales",
"Downham Market, Norfolk, England",
"Bath, Somerset, England",
"Horley, Surrey, England",
"Horley, Surrey, England",
"Halifax, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Stoke upon Trent, Staffordshire, England",
"",
"",
"",
"",
"",
"Halifax, West Yorkshire, England",
"Stoke upon Trent, Staffordshire, England",
"",
"",
"Halifax, West Yorkshire, England",
"",
"109 Louise Street, Burslem, Staffordshire, England",
"",
"Presteigne, Radnorshire, Wales",
"",
"Halifax, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"",
"Milton Keynes Hospital, Milton Keynes, Buckinghamshire, England",
"Luddenden, West Yorkshire, England",
"",
"",
"",
"",
"Nottingham, Nottinghamshire, England",
"",
"",
"Nottingham, Nottinghamshire, England",
"Radnorshire, Wales",
"",
"Totnes, Devon, England",
"",
"Sowerby Bridge, West Yorkshire, England",
"",
"",
"Halifax, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"",
"",
"",
"",
"",
"",
"Durban, South Africa",
"",
"",
"",
"Bournemouth, Dorset, England",
"Islington, London, England",
"",
"",
"",
"",
"",
"Rottingdean, East Sussex, England",
"64 College Street, Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"St. Ives, Cambridgeshire, England",
"Elsworth, Cambridgeshire, England",
"",
"West Ham, Greater London, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Wimbledon, Greater London, England",
"Leyburn, North Yorkshire, England",
"",
"",
"",
"",
"Georgetown, Demerara, Guyana",
"",
"",
"",
"",
"",
"",
"",
"",
"Hendon, London, England",
"Auckland, New Zealand",
"82 Littleton Street, Summerstown, London, England",
"Hastings, East Sussex, England",
"St Marks Hospital, Maidenhead, Berkshire, England",
"",
"",
"Crediton, Devon, England",
"Frimley, Surrey, England",
"",
"Exeter, Devon, England",
"26 Wolverton Avenue, Kingston on Thames, London, England",
"Exeter Royal Theatre, Exeter, Devon, England",
"Southwark, Greater London, England",
"Crediton, Devon, England",
"Cheshire, England",
"Exeter, Devon, England",
"Woking, Surrey, England",
"",
"",
"Gravesend, Kent, England",
"Bracknell, Berkshire, England",
"",
"",
"",
"Exeter, Devon, England",
"",
"",
"",
"Sutton, Greater London, England",
"",
"Redhill, Surrey, England",
"Beaford, Devon,England",
"Central Devon, England",
"Wandsworth, Greater London, England",
"Exeter, Devon, England",
"",
"Crowthorne, Berkshire, England",
"33 Rowan Drive, Crowthorne, Berkshire, England",
"Exeter, Devon, England",
"",
"55 Regent Square, Heavitree, Devon, England",
"Exeter Royal Theatre, Exeter, Devon, England",
"Redruth, Cornwall, England",
"New Zealand",
"Exeter, Devon, England",
"",
"",
"",
"Eastbourne, East Sussex, England",
"Plymouth, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Exeter Royal Theatre, Exeter, Devon, England",
"Newton Abbot, Devon, England",
"",
"Beckenham, Kent,England",
"Plymouth, Devon, England",
"Newton Abbot, Devon, England",
"Exeter, Devon, England",
"Exeter, Devon, England",
"Plymouth, Devon, England",
"",
"Cornwall,England",
"Crediton, Devon, England",
"Bedminster,Somerset,England",
"",
"",
"Wokingham, Berkshire, England",
"Exeter, Devon, England",
"Berkshire, England",
"Exeter, Devon, England",
"",
"Par, Cornwall, England",
"Plymouth, Devon, England",
"",
"",
"",
"Auckland, New Zealand",
"",
"",
"Crowthorne, Berkshire, England",
"",
"",
"Taunton, Somerset, England",
"Bristol, Gloucestershire, England",
"Warrington, Lancashire, England",
"Crediton, Devon, England",
"Cornwall,England",
"Crowthorne, Berkshire, England",
"Exeter, Devon, England",
"",
"",
"Chard, Somerset, England",
"Exeter, Devon, England",
"",
"St Agnes, Cornwall, England",
"",
"",
"",
"Surrey, England",
"",
"Crediton, Devon, England",
"",
"Devon, England",
"St Agnes, Cornwall, England",
"Gilpin,Colorado,USA",
"",
"Exeter, Devon, England",
"Crediton, Devon, England",
"",
"St Agnes, Cornwall, England",
"Exeter, Devon, England",
"Devonport, Devon, England",
"",
"Warrington, Lancashire, England",
"",
"",
"",
"Hull, Massachusetts, USA",
"",
"",
"",
"",
"",
"Leicester, Leicestershire, England",
"",
"Kelowna, British Columbia, Canada",
"",
"",
"",
"Luddenden, West Yorkshire, England",
"Horbury, West Yorkshire, England",
"Wakefield, West Yorkshire, England",
"Horbury, West Yorkshire, England",
"",
"Horbury, West Yorkshire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Lorborn Street, Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"Birstall, West Yorkshire, England",
"",
"Buckland Filleigh, Devon England",
"",
"",
"St Giles in the Wood, Devon, England",
"St Giles in the Wood, Devon, England",
"St Giles in the Wood, Devon, England",
"St Giles in the Wood, Devon, England",
"Leicester, Leicestershire, England",
"France",
"",
"",
"Leicester, Leicestershire, England",
"Salisbury, Wiltshire, England",
"Bosham, West Sussex, England",
"Winchester, Hampshire, England",
"Worthing, West Sussex, England",
"14 Caversham Street, Chelsesa, Borough of Kensington and Chelsea, Greater London, England",
"Woronora Memorial Park, Sutherland, New South Wales, Australia",
"",
"St Giles, Colchester, Essex, England",
"",
"",
"",
"St Giles, Colchester, Essex, England",
"",
"",
"",
"",
"Marrickville, New South Wales, Australia",
"",
"",
"St Giles, Colchester, Essex, England",
"",
"",
"",
"",
"",
"",
"",
"Buckland Brewer, Devon, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Chevening, Kent, England",
"",
"Buckland Brewer, Devon, England",
"",
"",
"",
"Pontypool, Monmouthshire, England",
"",
"Halifax, West Yorkshire, England",
"West Yorkshire, England",
"",
"",
"",
"",
"Devon, England",
"",
"Wigan, Greater Manchester, England",
"Wigan, Greater Manchester, England",
"",
"Saddleworth, Yorkshire, England",
"",
"Crediton, Devon, England",
"",
"",
"",
"",
"",
"",
"Crediton, Devon, England",
"",
"",
"Wapping, London, England",
"",
"",
"Mansfield, Nottingham, England",
"Wapping, London, England",
"",
"",
"",
"",
"",
"St Thomas, Devon, England",
"Wakefield, West Yorkshire, England",
"",
"",
"",
"",
"Lambeth, Greater London, England",
"Whitechapel, Greater London, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Canterbury, Kent, England",
"Stepney, London, England",
"",
"Edmonton, Greater London, England",
"",
"Leicester, Leicestershire, England",
"",
"Market Bosworth, Leicestershire, England",
"Leicester, Leicestershire, England",
"Leicester, Leicestershire, England",
"Leicestershire, England",
"Exeter, Devon, England",
"",
"",
"Lincolnshire, England",
"Ontario, Canada",
"Yorkshire, England",
"",
"Frontenac, Ontario, Canada",
"Vancouver, British Columbia, Canada",
"",
"Halifax, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Kelowna, British Columbia, Canada",
"Halifax, Nova Scotia, Canada",
"Halifax, West Yorkshire, England",
"Yorkshire, England",
"Halifax, West Yorkshire, England",
"Kempston, Bedfordshire, England",
"",
"Elland, West Yorkshire, England",
"Kingston, Ontario, Canada",
"Victoria, British Columbia, Canada",
"Victoria, British Columbia, Canada",
"Vancouver, British Columbia, Canada",
"",
"Halifax, Nova Scotia, Canada",
"Cook, Illinois, USA",
"",
"Halifax, West Yorkshire, England",
"",
"Todmorden, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Stafford, Staffordshire, England",
"Mulgrave, Nova Scotia, Canada",
"",
"12 Court Lane, Dulwich, London, England",
"",
"Victoria, British Columbia, Canada",
"Kelowna, British Columbia, Canada",
"Victoria, British Columbia, Canada",
"Vancouver, British Columbia, Canada",
"High Road, Halifax, West Yorkshire, England",
"",
"",
"",
"Halifax, West Yorkshire, England",
"",
"Camberwell,London,England",
"Horley, Surrey, England",
"",
"",
"Norton St Phillip, Somerset, England",
"",
"Surrey, England",
"",
"Alston,Cumbria,England",
"",
"",
"",
"",
"",
"",
"Lancashire,England",
"Bournheath,Worcestershire,England",
"Bournheath,Worcestershire,England",
"Birmingham,West Midlands,England",
"",
"",
"Bournheath,Worcestershire,England",
"Lancashire,England",
"Lancashire,England",
"Bury, Greater Manchseter, England",
"",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"High Street, Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"",
"",
"",
"",
"Sowerby Bridge, West Yorkshire, England",
"Warley, West Yorkshire, England",
"",
"",
"Camberwell,London,England",
"",
"",
"",
"",
"",
"",
"Mytholmroyd, West Yorkshire, England",
"",
"Halifax, West Yorkshire, England",
"",
"7 Windsor Avenue, New Maulden, Surrey, England",
"",
"Devon, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"East Molesey, Surrey, England",
"Plymouth, Devon, England",
"Lancashire,England",
"Malmesbury, Wiltshire, England",
"",
"",
"",
"",
"Ontario, Canada",
"Exeter, Devon, England",
"",
"",
"",
"Exeter Royal Theatre, Exeter, Devon, England",
"",
"",
"",
"Exeter, Devon, England",
"",
"",
"",
"St Ives, New South Wales, Australia",
"",
"Wootton Under Edge, Gloucestershire, England",
"",
"Carmarthen,Camarthenshire,Wales",
"",
"",
"Bexhill-on-Sea, East Sussex, England",
"Germany",
"",
"Kingston Upon Thames, Greater London, England",
"",
"",
"",
"",
"",
"7 Windsor Avenue, New Maulden, Surrey, England",
"London, England",
"",
"",
"",
"Haisborough, Norfolk, England",
"Plymouth, Devon, England",
"Plymouth, Devon, England",
"Paddington, Greater London, England",
"Tonbridge, Kent, England",
"Battersea, London,England",
"Wandsworth, Greater London, England",
"Horton Lane, Epsom, Surrey, England",
"Marylebone, Greater London, England",
"Point Clare, New South Wales, Australia",
"",
"Twyford, Berkshire, England",
"Hastings, East Sussex, England",
"40 Friars Vennel, Dumfries, Dumfries and Galloway, Scotland",
"Kilmarnock, Ayrshire, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"",
"",
"",
"Kentucky, USA",
"Lambeth, Greater London, England",
"",
"Croydon, Greater London, England",
"Godstone Union Workhouse, Godstone, Surrey, England",
"Godstone Union Workhouse, Godstone, Surrey, England",
"Godstone, Surrey, England",
"",
"Surrey, England",
"",
"Woodbridge, New Jersey, USA",
"",
"Godstone, Surrey, England",
"",
"Woodbridge, New Jersey, USA",
"Croydon, Greater London, England",
"",
"Surrey, England",
"",
"Surrey, England",
"Bethnal Green,London,England",
"Godstone, Surrey, England",
"Mansfield, Nottingham, England",
"",
"Dartford, Kent, England",
"",
"",
"",
"Exeter, Devon, England",
"",
"Heston, Greater London, England",
"Staffordshire, England",
"",
"",
"",
"",
"Plymouth, Devon, England",
"Plymouth, Devon, England",
"",
"Plymouth, Devon, England",
"",
"Plymouth, Devon, England",
"Plymouth, Devon, England",
"Plymouth, Devon, England",
"Exeter, Devon, England",
"",
"",
"",
"Plymouth, Devon, England",
"",
"",
"",
"",
"",
"Wigan, Greater Manchester, England",
"",
"",
"",
"Norland, West Yorkshire, England",
"",
"",
"",
"",
"",
"",
"Victoria, British Columbia, Canada",
"",
"",
"",
"",
"",
"",
"",
"Sowerby Bridge, West Yorkshire, England",
"",
"",
"",
"St Pancras, London, England",
"",
"Ashford",
"",
"",
"",
"Kensington, Greater London, England",
"",
"",
"",
"St Albans, Hertfordshire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Enfield, Greater London, England",
"",
"Huntingdon, Cambridgeshire, England",
"",
"St. Ives, Cambridgeshire, England",
"",
"",
"",
"",
"Dewsbury, West Yorkshire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Gloucester, Gloucestershire, England",
"",
"",
"Kenton, Greater London, England",
"",
"Horley, Surrey, England",
"",
"",
"",
"",
"",
"Amelia, Virginia, USA",
"",
"",
"",
"",
"",
"Staffordshire, England",
"",
"",
"",
"Newcastle under Lyme, Staffordshire, England",
"",
"Newcastle under Lyme, Staffordshire, England",
"",
"",
"Stoke upon Trent, Staffordshire, England",
"",
"",
"",
"",
"",
"Cheadle, Staffordshire, England",
"",
"",
"",
"Staffordshire, England",
"Staffordshire, England",
"Wolstanton, Staffordshire, England",
"Lincoln County, Kentucky, USA",
"",
"",
"London, England",
"St George's Hospital, Tooting, London, England",
"",
"Halifax, West Yorkshire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"Horley, Surrey, England",
"",
"Horley, Surrey, England",
"Croydon, Greater London, England",
"",
"London, England",
"Belvedere, London, England",
"",
"",
"",
"",
"Surrey, England",
"",
"",
"",
"",
"",
"Frimley, Surrey, England",
"",
"",
"",
"",
"Halifax, West Yorkshire, England",
"",
"Godstone Union Workhouse, Godstone, Surrey, England",
"",
"",
"Ipswich, Suffolk, England",
"",
"Swindon, Wiltshire, England",
"Enfield, Greater London, England",
"Edmonton, Greater London, England",
"Sutton, Greater London, England",
"Dacorum, Hertfordshire, England",
"Edmonton, Greater London, England",
"Enfield, Greater London, England",
"Bradford, West Yorkshire, England",
"",
"",
"",
"",
"Dorchester, Devon, England",
"Edmonton, Greater London, England",
"",
"Weymouth, Dorset, England",
"",
"British Columbia, Canada",
"",
"",
"",
"",
"",
"",
"Hillingdon, Greater London, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Todmorden, West Yorkshire, England",
"Yorkshire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"Pembrokeshire, Wales",
"",
"",
"",
"Orillia, Ontario, Canada",
"",
"Doncaster, South Yorkshire, England",
"",
"",
"",
"",
"Halifax, West Yorkshire, England",
"",
"",
"",
"",
"Windsor, Berkshire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Heston, Greater London, England",
"Wigan, Greater Manchester, England",
"",
"",
"",
"",
"",
"Bluntisham, Cambridgeshire, England",
"Gloucester, Gloucestershire, England",
"St Pancras, London, England",
"",
"",
"",
"Canterbury, Kent, England",
"",
"",
"Tankerton, Kent, England",
"Newcastle upon Tyne, Tyne and Wear, England",
"",
"Dauntsey, Wiltshire, England",
"",
"",
"",
"",
"",
"",
"Essex, England",
"",
"",
"Blackpool, Lancashire, England",
"",
"",
"",
"",
"West Yorkshire, England",
"Halifax, West Yorkshire, England",
"",
"Heptonstall, West Yorkshire, England",
"",
"Little Barrington, Gloucestershire, England",
"Prince Edward Island, Canada",
"New Zealand",
"",
"Langham, Suffolk, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Hampstead, Greater London, England",
"St Pancras, London, England",
"82 Littleton Street, Summerstown, London, England",
"",
"Enfield, Greater London, England",
"32 Hall Place, Paddington, London, England",
"East Molesey, Surrey, England",
"Milton Keynes, Buckinghamshire, England",
"Paddington, Greater London, England",
"Milton Keynes, Buckinghamshire, England",
"Kingston Upon Thames, Greater London, England",
"",
"Paddington, Greater London, England",
"Haringey, Greater London, England",
"Hounslow, Greater London, England",
"Middlesex, England",
"",
"",
"",
"",
"Stafford, Staffordshire, England",
"",
"",
"",
"",
"",
"",
"",
"St Giles, Colchester, Essex, England",
"",
"",
"",
"",
"",
"Exeter Royal Theatre, Exeter, Devon, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Lambeth, Greater London, England",
"Chichester, West Sussex, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Bletchingley, Surrey, England",
"",
"",
"Reigate, Surrey, England",
"",
"",
"",
"",
"",
"Godstone, Surrey, England",
"",
"",
"",
"",
"Bethnal Green,London,England",
"",
"",
"",
"",
"Almondbury, West Yorkshire, England",
"",
"",
"",
"Crawley, West Sussex, England",
"Westminster, Greater London, England",
"",
"",
"",
"",
"",
"",
"",
"",
"Hilmarton, Wiltshire, England",
"Wolstanton, Staffordshire, England",
"",
"",
"Almondbury, West Yorkshire, England",
"Heptonstall, West Yorkshire, England",
"",
"Peebles, Peeblesshire, Scotland",
"Invercargill, New Zealand",
"Scotland",
"",
"",
"",
"",
"",
"",
"Peebles, Peeblesshire, Scotland",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Leicestershire, England",
"Blaby, Leicesteshire",
"Thornton Heath, Greater London, England",
"",
"",
"",
"Ecclesall, South Yorkshire, England",
"",
"",
"",
"Hinckley, Leicestershire",
"",
"",
"Leicestershire, England",
"",
"",
"",
"",
"",
"",
"Edmonton, Greater London, England",
"",
"",
"",
"",
"Norwood Hill, Surrey, England",
"Islington, London, England",
"Dartford, Kent, England",
"",
"",
"",
"",
"",
"",
"",
"",
"Whitechapel, Greater London, England",
"",
"",
"",
"",
"Chichester, West Sussex, England",
"",
"",
"",
"",
"",
"",
"",
"Wirksworth, Derbyshire, England",
"",
"",
"",
"",
"",
"",
"Hexham, Northumberland, England",
"Newcastle upon Tyne, Tyne and Wear, England",
"",
"",
"",
"Woodbridge, New Jersey, USA",
"Lathbury, Buckinghamshire, England",
"New Hampshire, USA",
"Piscataway, New Jersey, USA",
"Piscataway, New Jersey, USA",
"Lyneham, Wiltshire, England",
"",
"Little Barrington, Gloucestershire, England",
"Little Barrington, Gloucestershire, England",
"St. Ives, Cambridgeshire, England",
"",
"",
"",
"",
"",
"",
"West Yorkshire, England",
"",
"Warden, Northumberland, England",
"Hexham, Northumberland, England",
"",
"",
"Dewsbury, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"",
"",
"Dewsbury, West Yorkshire, England",
"",
"",
"",
"",
"",
"",
"Leeds, West Yorkshire, England",
"",
"",
"Yorkshire, England",
"Ripponden, West Yorkshire, England",
"Camberwell,London,England",
"",
"",
"Dewsbury, West Yorkshire, England",
"",
"Ripponden, West Yorkshire, England",
"",
"Dewsbury, West Yorkshire, England",
"",
"Yorkshire, England",
"Ripponden, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"",
"Middlesex, England",
"Kingston Upon Thames, Greater London, England",
"South End, Essex, England",
"London, England",
"Brighton,East Sussex,England",
"British Columbia, Canada",
"",
"Crediton, Devon, England",
"",
"",
"",
"",
"Kingston, Ontario, Canada",
"Twyford, Berkshire, England",
"Plymouth, Devon, England",
"Prescott, Arizona, USA",
"Derby, Derbyshire, England",
"",
"Leicester, Leicestershire, England",
"",
"",
"",
"Plymouth, Devon, England",
"Sechelt, British Columbia, Canada",
"Henley, Oxfordshire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Andover, Hampshire, England",
"",
"",
"",
"",
"",
"",
"Halifax, West Yorkshire, England",
"",
"",
"",
"Sowerby Bridge, West Yorkshire, England",
"",
"",
"Warley, West Yorkshire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Exeter, Devon, England",
"",
"Exeter, Devon, England",
"Devon, England",
"Barnet, Hertfordshire, England",
"",
"Piscataway, New Jersey, USA",
"",
"",
"",
"",
"",
"",
"21 Shakespeare Street, Dumfries, Dumfries and Galloway, Scotland",
"30 Irish Street, Dumfries, Dumfries and Galloway, Scotland",
"Kirkcudbright, Kirkcudbrightshire, Scotland",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"26 Irish Street, Dumfries, Dumfries and Galloway, Scotland",
"",
"Invercargill, New Zealand",
"26 Irish Street, Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"34 Goldie Crescent, Dumfries, Dumfries and Galloway, Scotland",
"38 Munches Street, DUmfries, Dumfries and Galloway, Scotland",
"Hammersmith Hospital, Hammersmith, London, England",
"",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"Hillingdon, Greater London, England",
"66 Shakespeare Street, Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"",
"Roxburghshire, Scotland",
"",
"",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"France",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"Queens Cottages, Dumfries, Dumfries and Galloway, Scotland",
"14 Nith Place, Dumfries, Dumfries and Galloway, Scotland",
"",
"Park Royal Hospital, Brent, Middlesex, England",
"48 Sunderries Road, Dumfries, Dumfries and Galloway, Scotland",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"Wilton, Roxburghshire, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"149 High Street, Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"Clerkhill Cottage Burns Street, Dumfries, Dumfries and Galloway, Scotland",
"Tripoli,Libya",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"Kilmarnock, Ayrshire, Scotland",
"21 Shakespeare Street, Dumfries, Dumfries and Galloway, Scotland",
"19 Municipal Terrace, Dumfries, Dumfries and Galloway, Scotland",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"",
"",
"Colvend, Dumfries and Galloway, Scotland",
"",
"Dalbeattie, Dumfries and Galloway, Scotland",
"Michael Street, Dumfries",
"Kirkgunzeon, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"Jedburgh, Scottish Borders, Scotland",
"",
"Kirkcudbright, Kirkcudbrightshire, Scotland",
"Kirkpatrick Durham, Dumfries and Galloway, Scotland",
"Lochrutton, Kirkcudbrightshire, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"Bedford County, Virginia, USA",
"Dumfries, Dumfries and Galloway, Scotland",
"Lochrutton, Kirkcudbrightshire, Scotland",
"",
"",
"",
"",
"",
"",
"Parton, Kirkcudbrightshire, Scotland",
"",
"",
"",
"",
"86 Queen Street, Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Jefferson County, Ohio, USA",
"",
"",
"Lochrutton, Kirkcudbrightshire, Scotland",
"",
"26 Irish Street, Dumfries, Dumfries and Galloway, Scotland",
"Colora, Cecil, Maryland, USA",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Exeter, Devon, England",
"",
"",
"St Thomas, Devon, England",
"Bristol, Gloucestershire, England",
"",
"Exeter, Devon, England",
"Exeter, Devon, England",
"",
"",
"",
"Ipswich, Suffolk, England",
"Barton upon Irwell, Greater Manchester, England",
"Blaby, Leicesteshire",
"Victoria, British Columbia, Canada",
"",
"",
"Halifax, West Yorkshire, England",
"",
"",
"",
"",
"",
"",
"",
"Taunton, Somerset, England",
"",
"",
"Crowthorne, Berkshire, England",
"Twyford, Berkshire, England",
"",
"Ealing, Greater London, England",
"",
"",
"",
"",
"Victoria, British Columbia, Canada",
"",
"Newton Abbot, Devon, England",
"Totnes, Devon, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Park Royal Hospital, Brent, Middlesex, England",
"Peebles, Peeblesshire, Scotland",
"",
"Biggar, Lanarkshire, Scotland",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Blaby, Leicesteshire",
"",
"",
"",
"",
"Bluntisham, Cambridgeshire, England",
"Buckland Filleigh, Devon England",
"",
"",
"",
"",
"Exeter, Devon, England",
"Bromley, Borough of Bromley, Greater London, England",
"Exeter, Devon, England",
"",
"",
"",
"Kensington, Greater London, England",
"Frome, Somerset, England",
"",
"",
"",
"Middlesex, England",
"Enfield, Greater London, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Leicester, Leicestershire, England",
"Blaby, Leicesteshire",
"",
"",
"",
"Leicester, Leicestershire, England",
"",
"",
"",
"",
"",
"",
"",
"Leicester, Leicestershire, England",
"",
"Nottinghamshire, England",
"",
"",
"Blaby, Leicesteshire",
"",
"Blaby, Leicesteshire",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Crediton, Devon, England",
"",
"",
"",
"",
"",
"Halifax, West Yorkshire, England",
"",
"",
"Wigan, Greater Manchester, England",
"Blackpool, Lancashire, England",
"Belper, Derbyshire, England",
"",
"",
"Newcastle under Lyme, Staffordshire, England",
"Blackpool, Lancashire, England",
"France",
"",
"",
"",
"Blackpool, Lancashire, England",
"Wigan, Greater Manchester, England",
"Wigan, Greater Manchester, England",
"",
"Wigan, Greater Manchester, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Hendon, London, England",
"Harrow, England",
"",
"Hendon, London, England",
"Brent, Grater London, England",
"St Albans, Hertfordshire, England",
"",
"",
"Gloucestershire, England",
"Taunton, Somerset, England",
"",
"Ware, Hertfordshire, England",
"Worthing, West Sussex, England",
"Whitehaven, Cumbria, England",
"",
"38 Grosvenor Road, St Albans, Hertfordshire, England",
"",
"Zimbarbwae",
"Hendon, London, England",
"",
"",
"Harrow, England",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"",
"St Albans, Hertfordshire, England",
"",
"",
"Bristol, Gloucestershire, England",
"Winchester, Hampshire, England",
"",
"Ware, Hertfordshire, England",
"",
"Wapping, London, England",
"Alston,Cumbria,England",
"Kingsbury, London, England",
"",
"",
"",
"",
"",
"",
"Buckland Brewer, Devon, England",
"Crediton, Devon, England",
"",
"Buckland Filleigh, Devon England",
"",
"",
"",
"",
"Crediton, Devon, England",
"",
"Buckland Brewer, Devon, England",
"",
"",
"Crediton, Devon, England",
"",
"Buckland Filleigh, Devon England",
"",
"Oakhampton, Devon, England",
"Parkham, Devon, England",
"Buckland Filleigh, Devon England",
"Buckland Filleigh, Devon England",
"",
"Crediton, Devon, England",
"",
"",
"Whitchurch, Devon, England",
"",
"",
"Buckland Brewer, Devon, England",
"",
"",
"Parkham, Devon, England",
"",
"",
"Devon, England",
"Buckland Filleigh, Devon England",
"Parkham, Devon, England",
"",
"",
"Winscott, St Giles in the Wood, Devon, England",
"St Giles in the Wood, Devon, England",
"Crediton, Devon, England",
"Nanaimo, British Columbia, Canada",
"Yorkshire, England",
"Victoria, British Columbia, Canada",
"Hendon, London, England",
"Hendon, London, England",
"San Diego, California, USA",
"Salisbury, Wiltshire, England",
"Doncaster, South Yorkshire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Enfield, Greater London, England",
"",
"",
"",
"Mildenhall, Suffolk, England",
"",
"",
"St Agnes, Cornwall, England",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"",
"Hampstead, Greater London, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Horley, Surrey, England",
"Horley, Surrey, England",
"",
"",
"Horley, Surrey, England",
"Horley, Surrey, England",
"Horley, Surrey, England",
"Horley, Surrey, England",
"",
"",
"",
"",
"",
"Wandsworth, Greater London, England",
"",
"",
"",
"",
"",
"Camden, Greater London, England",
"",
"",
"",
"",
"",
"Kingston Upon Thames, Greater London, England",
"Wandsworth, Greater London, England",
"",
"Hessle, Yorkshire and the Humber, England",
"",
"",
"",
"",
"Abercynon, Rhondda Cynon Taf, Wales",
"Coningsby, Lincolnshire, England",
"Halifax, West Yorkshire, England",
"Bournemouth, Dorset, England",
"",
"New Zealand",
"London, England",
"",
"Bournemouth, Dorset, England",
"",
"",
"Crediton, Devon, England",
"Exeter, Devon, England",
"Totnes, Devon, England",
"Bournemouth, Dorset, England",
"",
"",
"",
"Wimborne, Dorset, England",
"Boston, Lincolnshire, England",
"Surrey, England",
"Epsom, Surrey, England",
"",
"",
"Victoria, British Columbia, Canada",
"Victoria, British Columbia, Canada",
"Yorkshire, England",
"",
"",
"",
"",
"",
"",
"Harrogate, North Yorkshire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Peebles, Peeblesshire, Scotland",
"Torquay, Devon, England",
"",
"",
"",
"",
"",
"",
"",
"Woking, Surrey, England",
"Leicester, Leicestershire, England",
"Havering, Greater London, England",
"Halifax, West Yorkshire, England",
"",
"",
"",
"",
"",
"Camberwell,London,England",
"",
"",
"Woolwich, Greater London, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Dalton-In-Furness, Lancashire, England",
"Carlisle, Cumbria, England",
"",
"Cumberland, England",
"",
"",
"",
"Durham, England",
"",
"",
"Elsworth, Cambridgeshire, England",
"",
"",
"Leicestershire, England",
"Markfield, Leicestershire, England",
"",
"Bluntisham, Cambridgeshire, England",
"Bluntisham, Cambridgeshire, England",
"",
"",
"Alberta, Canada",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Newcastle under Lyme, Staffordshire, England",
"222 Underhill Road, East Dulwich, London, England",
"",
"",
"",
"40 Government Street, Victoria, British Columbia, Canada",
"",
"",
"",
"Surrey, England",
"Halifax, West Yorkshire, England",
"",
"",
"Halifax, West Yorkshire, England",
"Blackpool, Lancashire, England",
"",
"",
"",
"Warley, West Yorkshire, England",
"",
"Horley, Surrey, England",
"",
"Halifax, West Yorkshire, England",
"Horley, Surrey, England",
"Glossop, Derbyshire, England",
"",
"",
"",
"Auckland, New Zealand",
"New Zealand",
"Camberwell,London,England",
"",
"",
"",
"",
"",
"",
"",
"Saddleworth, Yorkshire, England",
"",
"",
"Kensington, Greater London, England",
"",
"",
"Leicester, Leicestershire, England",
"Leicester, Leicestershire, England",
"Blaby, Leicesteshire",
"106 Enderby Road, Whetstone, Leicestershire, England",
"",
"Leicester, Leicestershire, England",
"Barrow upon Soar, Leicestershire, England",
"",
"",
"Leicester, Leicestershire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Kettering, Northhamptonshire, England",
"",
"",
"",
"",
"",
"Plymouth, Devon, England",
"Plymouth, Devon, England",
"",
"",
"",
"",
"",
"",
"Biggar, Lanarkshire, Scotland",
"Bluntisham, Cambridgeshire, England",
"Bluntisham, Cambridgeshire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Greenwich, Greenwich, Greater London, England",
"Worthing, West Sussex, England",
"",
"",
"",
"",
"",
"Leicester, Leicestershire, England",
"",
"Chicago, Illinois, USA",
"Crediton, Devon, England",
"",
"",
"Bluntisham, Cambridgeshire, England",
"",
"",
"",
"",
"",
"Warboys, Cambridgeshire, England",
"",
"",
"",
"",
"",
"",
"",
"Warrington, Lancashire, England",
"",
"",
"",
"",
"",
"",
"Enfield, Greater London, England",
"",
"",
"",
"",
"",
"",
"",
"",
"Chertsey, Surrey, England",
"",
"",
"Reigate, Surrey, England",
"Croydon, Greater London, England",
"Peebles, Peeblesshire, Scotland",
"Reigate, Surrey, England",
"Reigate, Surrey, England",
"",
"Surrey, England",
"Halifax, West Yorkshire, England",
"",
"Luddenden, West Yorkshire, England",
"",
"Halifax, West Yorkshire, England",
"Horsforth, Leeds ,England",
"West Yorkshire, England",
"Halifax, West Yorkshire, England",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"",
""
]
Dwr.ScriptLoaded('dwr_db_I_death_place_0.js');
