// This file is generated

I_birth_place_0 = [
"",
"",
"",
"Morchard Bishop, Devon, England",
"Barkby, Leicestershire, England",
"",
"Horbury, West Yorkshire, England",
"Lutterworth, Leicestershire, England",
"Whetstone, Leicestershire, England",
"",
"",
"",
"",
"Halifax, West Yorkshire, England",
"",
"",
"",
"",
"",
"",
"Cornwall,England",
"Whetstone, Leicestershire, England",
"Battle, East Sussex, England",
"",
"Bethnal Green,London,England",
"Exeter, Devon, England",
"",
"Devon, England",
"",
"",
"",
"",
"",
"",
"Leicester, Leicestershire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"Cornwall,England",
"Devon, England",
"New Hampshire, USA",
"",
"",
"",
"",
"",
"",
"St Agnes, Cornwall, England",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"Barlestone, Leicesteshire, England",
"",
"",
"Stapleton, Cumberland, England",
"",
"",
"",
"",
"",
"Quadring, Linconshire, England",
"Mells, Somerset, England",
"",
"Mary Tavy, Devon, England",
"Stoke upon Trent, Staffordshire, England",
"",
"",
"Wellesbourne, Warwickshire, England",
"",
"Lutterworth, Leicestershire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Chiselhurst, Greater London, England",
"Balham, Greater London, Enalgnd",
"Wandsworth, Greater London, England",
"Balham, Greater London, Enalgnd",
"",
"Balham, Greater London, Enalgnd",
"Chiselhurst, Greater London, England",
"Balham, Greater London, Enalgnd",
"Chiselhurst, Greater London, England",
"Balham, Greater London, Enalgnd",
"Roydon, Essex, England",
"Hoo, Kent, England",
"Chiselhurst, Greater London, England",
"Chiselhurst, Greater London, England",
"Chiselhurst, Greater London, England",
"",
"Balham, Greater London, Enalgnd",
"",
"",
"",
"",
"",
"",
"",
"",
"Clyst Hydon, Devon, England",
"Great Paxton, Cambrideshire,England",
"",
"",
"",
"Plymouth, Devon, England",
"Plymouth, Devon, England",
"Plymouth, Devon, England",
"",
"Devonport, Devon, England",
"Plymouth, Devon, England",
"Ontario, Canada",
"Ontario, Canada",
"Odessa, Ontario, Canada",
"",
"",
"Sedgley, West Midlands, England",
"",
"",
"",
"",
"",
"Crediton, Devon, England",
"",
"",
"Surrey, England",
"Lambeth, Greater London, England",
"Kensington, Greater London, England",
"Hendon, London, England",
"Wandsworth, Greater London, England",
"Lambeth, Greater London, England",
"",
"",
"",
"Wandsworth, Greater London, England",
"Battersea, London,England",
"Greenwich, Greenwich, Greater London, England",
"Surrey, England",
"Lambeth, Greater London, England",
"",
"",
"Battersea, London,England",
"",
"Greenwich, Greenwich, Greater London, England",
"Lambeth, Greater London, England",
"Southwark, Greater London, England",
"",
"",
"Wandsworth, Greater London, England",
"19 Reginald Road, Lambeth, Greater London, England",
"Wandsworth, Greater London, England",
"Wandsworth, Greater London, England",
"Lambeth, Greater London, England",
"",
"Lambeth, Greater London, England",
"",
"Battersea, London,England",
"",
"Lambeth, Greater London, England",
"Wandsworth, Greater London, England",
"Streatham, London, England",
"",
"",
"Wandsworth, Greater London, England",
"Lambeth, Greater London, England",
"",
"",
"",
"",
"",
"",
"",
"Wandsworth, Greater London, England",
"",
"",
"",
"",
"",
"Lambeth, Greater London, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Reigate, Surrey, England",
"",
"Ewell, Surrey, England",
"Ewell, Surrey, England",
"Wootton Under Edge, Gloucestershire, England",
"Great Sampford, Essex, England",
"Suffolk, England",
"Suffolk, England",
"Ewell, Surrey, England",
"Gravesend, Kent, England",
"Horley, Surrey, England",
"Nutfield, Surrey, England",
"Sowerby Bridge, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Burton upon Trent, Staffordshire, England",
"",
"Halifax, West Yorkshire, England",
"",
"Crewe, Cheshire, England",
"",
"Sowerby Bridge, West Yorkshire, England",
"Burslem,Staffordshire,England",
"Wolstanton, Staffordshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Nantwich, Cheshire, England",
"Halifax, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Crewe, Cheshire, England",
"Hanley, Staffordshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Newcastle under Lyme, Staffordshire, England",
"Sowerby Bridge, West Yorkshire, England",
"",
"",
"Sowerby Bridge, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Warley, West Yorkshire, England",
"Pudsey, West yorkshire, England",
"Halifax, West Yorkshire, England",
"Nantwich, Cheshire, England",
"",
"Newcastle under Lyme, Staffordshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"",
"Sowerby Bridge, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"",
"St Pancras, London, England",
"St Pancras, London, England",
"",
"",
"",
"Zimbarbwae",
"Lewisham, Borough of Lewisham, Greater London, England",
"Capel, Surrey, England",
"",
"Cross Keys, Gwent,  Wales",
"Islington, London, England",
"Brixton, Surrey, England",
"",
"",
"",
"",
"Richmond, Greater London, England",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"Graveley, Cambridgeshire, England",
"Elsworth, Cambridgeshire, England",
"Graveley, Cambridgeshire, England",
"Chester, Cheshire, England",
"Bethnal Green,London,England",
"",
"Ontario, Canada",
"Ontario, Canada",
"",
"Penge, Bromley, Greater London, England",
"",
"",
"",
"",
"Guiana",
"Borough of Kensington and Chelsea, London, England",
"",
"",
"",
"",
"Barbados",
"",
"",
"",
"",
"",
"",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"Hanover Square, Westminster, Greater London, England",
"Auckland, New Zealand",
"Crediton, Devon, England",
"Southwark, Greater London, England",
"Crediton, Devon, England",
"",
"",
"Crediton, Devon, England",
"",
"",
"",
"Exeter, Devon, England",
"Dean Street, Crediton, Devon,England",
"Exeter, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Exeter, Devon, England",
"Exeter, Devon, England",
"Wandsworth, Greater London, England",
"St Agnes, Cornwall, England",
"St Agnes, Cornwall, England",
"Holsworthy, Devon",
"Crediton, Devon, England",
"Exeter, Devon, England",
"",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Exeter, Devon, England",
"Exeter, Devon, England",
"St Thomas, Devon, England",
"Holsworthy, Devon",
"Holsworthy, Devon",
"Exeter, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Wandsworth, Greater London, England",
"Crediton, Devon, England",
"",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Exeter, Devon, England",
"Exeter, Devon, England",
"Exeter, Devon, England",
"Exeter, Devon, England",
"Southleigh, Devon, England",
"Exeter, Devon, England",
"Crediton, Devon, England",
"",
"",
"Crediton, Devon, England",
"Wandsworth, Greater London, England",
"Redruth, Cornwall, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Devon, England",
"Exeter, Devon, England",
"Wandsworth, Greater London, England",
"Holsworthy, Devon",
"Crediton, Devon, England",
"Exeter, Devon, England",
"Crediton, Devon, England",
"Exeter, Devon, England",
"",
"Cornwall,England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"",
"Crowthorne, Berkshire, England",
"",
"Easthampstead, Berkshire, England",
"Exeter, Devon, England",
"Andaman Islands, India",
"Crediton, Devon, England",
"East Down, Devon, England",
"",
"St Agnes, Cornwall, England",
"St Agnes, Cornwall, England",
"Exeter, Devon, England",
"Glasgow, Lanarkshire, England",
"",
"Southwark, Greater London, England",
"",
"",
"Chard, Somerset, England",
"Helston, Cornwall,England",
"Exeter, Devon, England",
"St Agnes, Cornwall, England",
"St Agnes, Cornwall, England",
"Tooting, Greater London, England",
"Exeter, Devon, England",
"Exeter, Devon, England",
"",
"Crediton, Devon, England",
"Devon, England",
"",
"Cornwall,England",
"St Agnes, Cornwall, England",
"St Agnes, Cornwall, England",
"St Agnes, Cornwall, England",
"Exeter, Devon, England",
"",
"Crediton, Devon, England",
"Exeter, Devon, England",
"Crediton, Devon, England",
"St Agnes, Cornwall, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"St Agnes, Cornwall, England",
"St Agnes, Cornwall, England",
"Exeter, Devon, England",
"Crediton, Devon, England",
"Southleigh, Devon, England",
"Exeter, Devon, England",
"",
"",
"",
"Caversham, Berkshire, England",
"Brixton, Surrey, England",
"Kensington, Greater London, England",
"Lambeth, Greater London, England",
"Brixton, Surrey, England",
"Brixton, Surrey, England",
"Leicester, Leicestershire, England",
"Leicester, Leicestershire, England",
"",
"",
"Brixton, Surrey, England",
"",
"",
"Halifax, West Yorkshire, England",
"Heptonstall, West Yorkshire, England",
"Wakefield, West Yorkshire, England",
"Wakefield, West Yorkshire, England",
"",
"Horbury, West Yorkshire, England",
"Leeds, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Bury, Greater Manchseter, England",
"Halifax, West Yorkshire, England",
"Manchester, Greater Manchester, England",
"",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"28 English Street, Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"Mirfield, Yorkshire, England",
"",
"St Giles in the Wood, Devon, England",
"",
"St Giles in the Wood, Devon, England",
"Devon, England",
"Devon, England",
"",
"St Giles in the Wood, Devon, England",
"Countesthorpe, Leicestershire, England",
"Wigston, Leicestershire, England",
"Leicestershire, England",
"Wigston, Leicestershire, England",
"Wigston, Leicestershire, England",
"Buckinghamshire, England",
"Harrow, England",
"Hendon, London, England",
"St Pancras, London, England",
"105 High Street, Marylebone, London, England",
"Balmain, Australia",
"London, England",
"Colchester,Essex,England",
"Marylebone, Greater London, England",
"Hendon, London, England",
"",
"",
"",
"",
"Marylebone, Greater London, England",
"Colchester,Essex,England",
"London, England",
"Colchester,Essex,England",
"Marylebone, Greater London, England",
"",
"Brett Road,Colchester,Essex,England",
"",
"",
"",
"",
"",
"",
"",
"Sutcombe, Devon, England",
"Sutcombe, Devon, England",
"",
"",
"Huntingdon, Cambridgeshire, England",
"Huntingdon, Cambridgeshire, England",
"Huntingdon, Cambridgeshire, England",
"Huntingdon, Cambridgeshire, England",
"",
"Huntingdon, Cambridgeshire, England",
"Huntingdon, Cambridgeshire, England",
"",
"Huntingdon, Cambridgeshire, England",
"Huntingdon, Cambridgeshire, England",
"Huntingdon, Cambridgeshire, England",
"Huntingdon, Cambridgeshire, England",
"",
"Huntingdon, Cambridgeshire, England",
"Huntingdon, Cambridgeshire, England",
"Huntingdon, Cambridgeshire, England",
"Huntingdon, Cambridgeshire, England",
"Eaton Bray, Bedfordshire, England",
"",
"Devon, England",
"Exbourne, Devon, England",
"Ireland",
"Petersfield, Hampshire, England",
"Launceston, Cornwall, England",
"Elland, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"West Yorkshire, England",
"",
"",
"Lambeth, Greater London, England",
"",
"Glasgow, Lanarkshire, England",
"",
"Wigan, Greater Manchester, England",
"Wigan, Greater Manchester, England",
"Saddleworth, Yorkshire, England",
"Saddleworth, Yorkshire, England",
"Crediton, Devon, England",
"St Thomas, Devon, England",
"",
"Crediton, Devon, England",
"",
"Crediton, Devon, England",
"Sidbury, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Ovenden, West Yorkshire, England",
"",
"",
"Wapping, London, England",
"",
"Wapping, London, England",
"Stepney, London, England",
"Wapping, London, England",
"Rainham, Kent, England",
"Leeds, West Yorkshire, England",
"",
"Leeds, West Yorkshire, England",
"Kirkgunzeon, Dumfries and Galloway, Scotland",
"Exeter, Devon, England",
"Horbury, West Yorkshire, England",
"",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"Yorkshire, England",
"Bethnal Green,London,England",
"Bethnal Green,London,England",
"Maidenhead, Berkshire, England",
"",
"Maidenhead, Berkshire, England",
"Maidenhead, Berkshire, England",
"Bletchingley, Surrey, England",
"Reigate, Surrey, England",
"Maidenhead, Berkshire, England",
"Maidenhead, Berkshire, England",
"West Ham, Greater London, England",
"Hungerford, Berkshire, England",
"Cookham, Berkshire, England",
"Cookham, Berkshire, England",
"Marylebone, Greater London, England",
"",
"",
"Virginia, USA",
"Great Paxton, Cambrideshire,England",
"Great Paxton, Cambrideshire,England",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"Great Staughton, Cambridgeshire, England",
"",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"",
"Kent, England",
"Dartford, Kent, England",
"Dartford, Kent, England",
"Markfield, Leicestershire, England",
"Markfield, Leicestershire, England",
"Markfield, Leicestershire, England",
"Leicestershire, England",
"Swannington, Leicestershire, England",
"Leicestershire, England",
"Leicestershire, England",
"Markfield, Leicestershire, England",
"Exeter, Devon, England",
"",
"Derbyshire, England",
"",
"Scotland",
"",
"Warley, West Yorkshire, England",
"Elland, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Vancouver, British Columbia, Canada",
"Sowerby Bridge, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Vancouver, British Columbia, Canada",
"Beaver Bank, Nova Scotia, Canada",
"Warley, West Yorkshire, England",
"Warley, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Dulwich, Greater London, England",
"Frontenac, Ontario, Canada",
"Halifax, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Victoria, British Columbia, Canada",
"Halifax, West Yorkshire, England",
"Vancouver, British Columbia, Canada",
"Frontenac, Ontario, Canada",
"Beaver Bank, Nova Scotia, Canada",
"Sowerby Bridge, West Yorkshire, England",
"",
"Warley, West Yorkshire, England",
"",
"Warley, West Yorkshire, England",
"High Road, Halifax, West Yorkshire, England",
"Warley, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Camberwell,London,England",
"Warley, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Greetland, West Yorkshire, England",
"",
"Halifax, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Frontenac, Ontario, Canada",
"Warley, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Nutfield, Surrey, England",
"Horbury, West Yorkshire, England",
"",
"Middlesex, England",
"",
"",
"",
"Alston,Cumbria,England",
"",
"",
"Tunstall, Staffordshire, England",
"",
"",
"Salford, Greater Manchester, England",
"Lancashire,England",
"Salford, Greater Manchester, England",
"Salford, Greater Manchester, England",
"Lancashire,England",
"Manchester, Greater Manchester, England",
"Salford, Greater Manchester, England",
"Salford, Greater Manchester, England",
"Salford, Greater Manchester, England",
"Lancashire,England",
"Salford, Greater Manchester, England",
"Pendleton, Lancashire, England",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"Torthorwald, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"Bedford, Bedfordshire, England",
"",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"Bedford, Bedfordshire, England",
"Bedford, Bedfordshire, England",
"",
"Halifax, West Yorkshire, England",
"",
"Halifax, West Yorkshire, England",
"",
"Redfield, Bristol, England",
"Camberwell,London,England",
"Barton Regis, Gloucestershire, England",
"",
"",
"",
"",
"Erringden, West Yorkshire, England",
"Mytholmroyd, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Erringden, West Yorkshire, England",
"7 Windsor Avenue, New Maulden, Surrey, England",
"",
"Barnstaple, Devon, England",
"Horsforth, Leeds ,England",
"Horsforth, Leeds ,England",
"",
"Horsforth, Leeds ,England",
"Horsforth, Leeds ,England",
"",
"",
"",
"",
"Silverdale, Staffordshire, England",
"Silverdale, Staffordshire, England",
"Silverdale, Staffordshire, England",
"Chapel Allerton, West Yorkshire, England",
"Silverdale, Staffordshire, England",
"Silverdale, Staffordshire, England",
"East Molesey, Surrey, England",
"Conway, Wales",
"Bournheath,Worcestershire,England",
"Kingston Upon Thames, Greater London, England",
"",
"Chapel Allerton, West Yorkshire, England",
"",
"Exeter, Devon, England",
"Ontario, Canada",
"Ontario, Canada",
"Exeter, Devon, England",
"Exeter, Devon, England",
"Ontario, Canada",
"Exeter, Devon, England",
"Exeter, Devon, England",
"Ontario, Canada",
"Ontario, Canada",
"Exeter, Devon, England",
"Plymouth, Devon, England",
"Ontario, Canada",
"Exeter, Devon, England",
"Ontario, Canada",
"Thackaringa, New South Wales, Australia",
"Reigate, Surrey, England",
"Reigate, Surrey, England",
"Reigate, Surrey, England",
"Redhill, Surrey, England",
"Reigate, Surrey, England",
"",
"13 Well Street, Whitechapel, London, England",
"Wandsworth, Greater London, England",
"",
"Tooting, Greater London, England",
"",
"KentIsh Town, Greater London, England",
"",
"",
"",
"Hampstead, Greater London, England",
"Westminster, Greater London, England",
"",
"",
"",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Paddington, Greater London, England",
"Paddington, Greater London, England",
"Paddington, Greater London, England",
"Paddington, Greater London, England",
"Paddington, Greater London, England",
"Marylebone, Greater London, England",
"32 Hall Place, Paddington, London, England",
"Trinidad and Tobago",
"Ruscombe, Berkshire, England",
"Fulham, Greater London, England",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"Annan, Dumfries and Galloway, Scotland",
"Hoddom, Dumfries and Galloway, Scotland",
"Hoddom, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"Hoddom, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"Essex, New Jersey, USA",
"Bethnal Green,London,England",
"Godstone, Surrey, England",
"Bletchingley, Surrey, England",
"Bletchingley, Surrey, England",
"Bletchingley, Surrey, England",
"Bletchingley, Surrey, England",
"Bletchingley, Surrey, England",
"Godstone, Surrey, England",
"Reigate, Surrey, England",
"Surrey, England",
"Bletchingley, Surrey, England",
"Godstone, Surrey, England",
"",
"Woodbridge, New Jersey, USA",
"Bletchingley, Surrey, England",
"Bletchingley, Surrey, England",
"Bletchingley, Surrey, England",
"Bletchingley, Surrey, England",
"Bletchingley, Surrey, England",
"Bethnal Green,London,England",
"Reigate, Surrey, England",
"Bletchingley, Surrey, England",
"Watford",
"Hackney, London, England",
"Islington, London, England",
"Islington, London, England",
"Islington, London, England",
"Islington, London, England",
"Islington, London, England",
"",
"",
"Luton, Bedfordshire, England",
"",
"Exeter, Devon, England",
"Fulham, Greater London, England",
"Hammersmith, Gerater London, England",
"Burslem,Staffordshire,England",
"Bodmin, Cornwall, England",
"",
"",
"",
"Plymouth, Devon, England",
"Plymouth, Devon, England",
"",
"",
"Plymouth, Devon, England",
"",
"St Thomas, Devon, England",
"Plymouth, Devon, England",
"Exeter, Devon, England",
"Plymouth, Devon, England",
"Plymouth, Devon, England",
"Plymouth, Devon, England",
"",
"",
"",
"",
"",
"",
"",
"Bolton, Lancashire, England",
"Crediton, Devon, England",
"",
"Devon, England",
"Heptonstall, West Yorkshire, England",
"Bluntisham, Cambridgeshire, England",
"",
"",
"",
"",
"",
"Victoria, British Columbia, Canada",
"",
"Dorchester, Devon, England",
"",
"",
"Luddenden, West Yorkshire, England",
"",
"Luddenden, West Yorkshire, England",
"",
"",
"Midgley, Yorkshire, England",
"",
"Luddenden, West Yorkshire, England",
"St Pancras, London, England",
"St Pancras, London, England",
"Huntingdon, Cambridgeshire, England",
"St Pancras, London, England",
"Huntingdon, Cambridgeshire, England",
"Huntingdon, Cambridgeshire, England",
"",
"London, England",
"Huntingdon, Cambridgeshire, England",
"Huntingdon, Cambridgeshire, England",
"Huntingdon, Cambridgeshire, England",
"St Pancras, London, England",
"Huntingdon, Cambridgeshire, England",
"Huntingdon, Cambridgeshire, England",
"St Pancras, London, England",
"St Pancras, London, England",
"St Pancras, London, England",
"Huntingdon, Cambridgeshire, England",
"",
"",
"",
"",
"",
"Biggleswade, Bedfordshire, England",
"",
"",
"",
"",
"St Pancras, London, England",
"St Pancras, London, England",
"St Pancras, London, England",
"Huntingdon, Cambridgeshire, England",
"Huntingdon, Cambridgeshire, England",
"Huntingdon, Cambridgeshire, England",
"St Pancras, London, England",
"",
"St Pancras, London, England",
"Huntingdon, Cambridgeshire, England",
"Heckmondwike, West Yorkshire, England",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Bisley, Gloucestershire, England",
"",
"",
"Harrow, England",
"Horley, Surrey, England",
"Horley, Surrey, England",
"Horley, Surrey, England",
"Silverdale, Staffordshire, England",
"Silverdale, Staffordshire, England",
"Fenton, Staffordshire, England",
"",
"Virginia, USA",
"Silverdale, Staffordshire, England",
"Tunstall, Staffordshire, England",
"Silverdale, Staffordshire, England",
"",
"",
"Staffordshire, England",
"Silverdale, Staffordshire, England",
"Shelton, Staffordshire, England",
"",
"Nottinghamshire, England",
"Silverdale, Staffordshire, England",
"Derbyshire, England",
"Fenton, Staffordshire, England",
"",
"Derby, Derbyshire, England",
"",
"",
"Talke On The Hill, Staffordshire, England",
"Silverdale, Staffordshire, England",
"Silverdale, Staffordshire, England",
"Wolstanton, Staffordshire, England",
"Burslem,Staffordshire,England",
"",
"",
"Derbyshire, England",
"Nottinghamshire, England",
"Hanley, Staffordshire, England",
"Virginia, USA",
"",
"Silverdale, Staffordshire, England",
"Demerara, British Guiana",
"Georgetown, Demerara, Guyana",
"Halifax, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"",
"Halifax, West Yorkshire, England",
"",
"Halifax, West Yorkshire, England",
"",
"7 Windsor Avenue, New Maulden, Surrey, England",
"",
"Church of St. Dunstan in the West, Fleet Street, London, England",
"",
"",
"Worthing, West Sussex, England",
"Chatham, Kent, England",
"",
"",
"",
"",
"Fulham, Greater London, England",
"",
"",
"",
"",
"",
"",
"",
"",
"Luddenden, West Yorkshire, England",
"Thornton in Lonsdale, North Yorkshire, England",
"Thornton in Lonsdale, North Yorkshire, England",
"St Pancras, London, England",
"Godstone, Surrey, England",
"",
"",
"Edmonton, Greater London, England",
"Barnet, Hertfordshire, England",
"Edmonton, Greater London, England",
"Edmonton, Greater London, England",
"Dorton, Buckinghamshire, England",
"Edmonton, Greater London, England",
"Edmonton, Greater London, England",
"Barnet, Greater London, England",
"Enfield, Greater London, England",
"Halifax, West Yorkshire, England",
"",
"",
"Warboys, Cambridgeshire, England",
"",
"Exeter, Devon, England",
"Exeter, Devon, England",
"Exeter, Devon, England",
"Exeter, Devon, England",
"Exeter, Devon, England",
"",
"Hanover Square, Westminster, Greater London, England",
"",
"Middlesex, England",
"",
"",
"",
"St. Ives, Cambridgeshire, England",
"Winlaton, Tyne and Wear, England",
"",
"",
"",
"",
"",
"",
"",
"Canada",
"Wandsworth, Greater London, England",
"Blackshaw Head, Yorkshire, England",
"Halifax, West Yorkshire, England",
"Luddenden, West Yorkshire, England",
"Yorkshire, England",
"Luddenden, West Yorkshire, England",
"",
"Peebles, Peeblesshire, Scotland",
"Liberton, Edinburgh, Scotland",
"",
"",
"",
"",
"",
"",
"Beaver Bank, Nova Scotia, Canada",
"",
"Abergavenny, Monmouthshire, Wales",
"",
"",
"",
"",
"Halifax, West Yorkshire, England",
"",
"",
"Edmonton, Greater London, England",
"Heptonstall, West Yorkshire, England",
"Luddenden, West Yorkshire, England",
"",
"Crediton, Devon, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Wigan, Greater Manchester, England",
"",
"",
"",
"",
"St Giles, Greater London, England",
"Huntingdon, Cambridgeshire, England",
"Strand, London, England",
"St Giles, Greater London, England",
"St Giles, Greater London, England",
"Huntingdon, Cambridgeshire, England",
"St Pancras, London, England",
"Hackney, London, England",
"St Giles, Greater London, England",
"St Giles, Greater London, England",
"Hackney, London, England",
"Hackney, London, England",
"St Giles, Greater London, England",
"Hilmarton, Wiltshire, England",
"",
"Hilmarton, Wiltshire, England",
"",
"",
"",
"Hackney, London, England",
"",
"",
"Ontario, Canada",
"",
"",
"Eccleshill, Lancashire, England",
"",
"Sowerby Bridge, West Yorkshire, England",
"Heptonstall, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Heptonstall, West Yorkshire, England",
"",
"Little Barrington, Gloucestershire, England",
"Annan, Dumfries and Galloway, Scotland",
"Greymouth, New Zealand",
"",
"Hunston, Suffolk,England",
"",
"Havre, France",
"",
"",
"",
"Wandsworth, Greater London, England",
"",
"",
"Devon, England",
"Newbury, Berkshire, England",
"Marylebone, Greater London, England",
"Islington, London, England",
"Marylebone, Greater London, England",
"Marylebone, Greater London, England",
"St Pancras, London, England",
"Marylebone, Greater London, England",
"Marylebone, Greater London, England",
"St Pancras, London, England",
"Middlesex, England",
"St Pancras, London, England",
"Marylebone, Greater London, England",
"Marylebone, Greater London, England",
"Marylebone, Greater London, England",
"St Pancras, London, England",
"St Pancras, London, England",
"Frome, Somerset, England",
"Finchely, Barnet, Greater London, England",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"Finchely, Barnet, Greater London, England",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"Finchely, Barnet, Greater London, England",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"",
"",
"",
"",
"",
"Exeter, Devon, England",
"",
"",
"",
"Exeter, Devon, England",
"",
"",
"",
"",
"",
"",
"",
"Heavitree, Devon, England",
"",
"",
"Oxfordshire, England",
"",
"",
"",
"Halifax, West Yorkshire, England",
"",
"",
"Bletchingley, Surrey, England",
"",
"",
"",
"",
"Bluntisham, Cambridgeshire, England",
"Bluntisham, Cambridgeshire, England",
"Bluntisham, Cambridgeshire, England",
"Bluntisham, Cambridgeshire, England",
"Alconbury-Cum-Weston, Cambridgeshire, England",
"Bluntisham, Cambridgeshire, England",
"Peebles, Peeblesshire, Scotland",
"",
"Wincanton, Somerset, England",
"",
"Yorkshire, England",
"Deptford, Greater London, England",
"",
"Bletchingley, Surrey, England",
"",
"",
"St. Ives, Cambridgeshire, England",
"Bletchingley, Surrey, England",
"",
"Bletchingley, Surrey, England",
"Bletchingley, Surrey, England",
"Bletchingley, Surrey, England",
"Bletchingley, Surrey, England",
"",
"",
"Surrey, England",
"Bletchingley, Surrey, England",
"Bletchingley, Surrey, England",
"Patringon, East Yorkshire, England",
"",
"",
"",
"Horsington, Somerset, England",
"",
"",
"",
"",
"Heptonstall, West Yorkshire, England",
"Bluntisham, Cambridgeshire, England",
"",
"West Ham, Greater London, England",
"Wandsworth, Greater London, England",
"Aston Cantlow, Warwickshire, England",
"",
"Heptonstall, West Yorkshire, England",
"",
"",
"",
"",
"",
"",
"Atworth, Wiltshire, England",
"Staffordshire, England",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"Almondbury, West Yorkshire, England",
"Heptonstall, West Yorkshire, England",
"",
"Peebles, Peeblesshire, Scotland",
"Peebles, Peeblesshire, Scotland",
"Peebles, Peeblesshire, Scotland",
"",
"Peebles, Peeblesshire, Scotland",
"Peebles, Peeblesshire, Scotland",
"",
"",
"",
"Peebles, Peeblesshire, Scotland",
"",
"Peebles, Peeblesshire, Scotland",
"Andover, Hampshire, England",
"Nantwich, Cheshire, England",
"Buckley, Flintshire, Wales",
"",
"Brett Road,Colchester,Essex,England",
"",
"",
"Leicester, Leicestershire, England",
"Sheffield, South Yorkshire, England",
"Leicestershire, England",
"Bitteswell, Leicestershire, England",
"Bitteswell, Leicestershire, England",
"Nether Hallam, Sheffield",
"Leicestershire, England",
"Leicester, Leicestershire, England",
"Bitteswell, Leicestershire, England",
"Bitteswell, Leicestershire, England",
"Sheffield, South Yorkshire, England",
"Bitteswell, Leicestershire, England",
"Sheffield, South Yorkshire, England",
"Bitteswell, Leicestershire, England",
"Leicester, Leicestershire, England",
"Leicestershire, England",
"Bitteswell, Leicestershire, England",
"Leicestershire, England",
"Bitteswell, Leicestershire, England",
"Bitteswell, Leicestershire, England",
"Leicestershire, England",
"Mortlake, Greater London, England",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"Bethnal Green,London,England",
"Bethnal Green,London,England",
"Stepney, London, England",
"Bethnal Green,London,England",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"Bethnal Green,London,England",
"Bethnal Green,London,England",
"Bexleyheath, Greater London, England",
"Bethnal Green,London,England",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"Bethnal Green,London,England",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"Bethnal Green,London,England",
"Bethnal Green,London,England",
"",
"",
"",
"Glasgow, Lanarkshire, England",
"",
"",
"Wandsworth, Greater London, England",
"",
"",
"",
"Marylebone, Greater London, England",
"",
"",
"",
"Wirksworth, Derbyshire, England",
"",
"",
"",
"",
"Reigate, Surrey, England",
"",
"",
"Hexham, Northumberland, England",
"",
"",
"Isle of Mann, UK",
"Woodbridge, New Jersey, USA",
"Lathbury, Buckinghamshire, England",
"Durham, England",
"Dover, New Hampshire, USA",
"Piscataway, New Jersey, USA",
"Lydiard Millicent, Wiltshire, England",
"",
"Little Barrington, Gloucestershire, England",
"Little Barrington, Gloucestershire, England",
"Meldreth, Cambridgeshire, England",
"",
"",
"",
"",
"Auckland, New Zealand",
"",
"Cononley, North Yorkshire, England",
"",
"",
"Warden, Northumberland, England",
"Peebles, Peeblesshire, Scotland",
"",
"Halifax, West Yorkshire, England",
"Warley, West Yorkshire, England",
"Yorkshire, England",
"Ripponden, West Yorkshire, England",
"Warley, West Yorkshire, England",
"Ripponden, West Yorkshire, England",
"Ripponden, West Yorkshire, England",
"Ripponden, West Yorkshire, England",
"Ripponden, West Yorkshire, England",
"Ripponden, West Yorkshire, England",
"Ripponden, West Yorkshire, England",
"Warley, West Yorkshire, England",
"Ripponden, West Yorkshire, England",
"Ripponden, West Yorkshire, England",
"Soyland, West Yorkshire, England",
"Ripponden, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Ripponden, West Yorkshire, England",
"Ripponden, West Yorkshire, England",
"Warley, West Yorkshire, England",
"Ripponden, West Yorkshire, England",
"Ripponden, West Yorkshire, England",
"",
"Warley, West Yorkshire, England",
"Ripponden, West Yorkshire, England",
"Soyland, West Yorkshire, England",
"Ripponden, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Kirkurd, Peebleshire, Scotland",
"Ivinghoe, Buckinghamshire, England",
"Kent, England",
"Lambeth, Greater London, England",
"Lambeth, Greater London, England",
"Clapham, Greater London, England",
"Lambeth, Greater London, England",
"Lambeth, Greater London, England",
"Crediton, Devon, England",
"",
"",
"",
"",
"",
"Wirral, Mersyside, England",
"Kingswood, Gloucestershire, England",
"",
"Whetstone, Leicestershire, England",
"Whetstone, Leicestershire, England",
"",
"Whetstone, Leicestershire, England",
"Whetstone, Leicestershire, England",
"Whetstone, Leicestershire, England",
"Whetstone, Leicestershire, England",
"Plymouth, Devon, England",
"",
"Reading, Berkshire, England",
"",
"",
"Cambridge, Cambridgeshire, England",
"Yorkshire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Camberwell,London,England",
"Medway, Kent, England",
"Aylesbury, Buckinghamshire, England",
"Leytonstone, Greter London, England",
"",
"",
"",
"",
"",
"Luddenden, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Midgley, Yorkshire, England",
"",
"",
"Luddenden, West Yorkshire, England",
"Midgley, Yorkshire, England",
"",
"Halifax, West Yorkshire, England",
"",
"",
"",
"",
"",
"Birmingham,West Midlands,England",
"",
"",
"Plymouth, Devon, England",
"Bromley, Borough of Bromley, Greater London, England",
"",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Bethnal Green,London,England",
"",
"Dover, New Hampshire, USA",
"St Giles in the Wood, Devon, England",
"Morwenstow, Cornwall, England",
"",
"",
"",
"India",
"Springholm, Kirkcudbrightshire, Scotland",
"Ireland",
"Kirkcudbright, Kirkcudbrightshire, Scotland",
"",
"Middlebie, Dumfries and Galloway, Scotland",
"Ettrick, Selkirk, Scotland",
"",
"",
"Ireland",
"Ireland",
"",
"Canada",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"Troqueer, Dumfries and Galloway, Scotland",
"",
"48 Sunderries Road, Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"",
"12 Irish Street, Dumfries, Dumfries and Galloway, Scotland",
"Clerkhill Cottage Burns Street, Dumfries, Dumfries and Galloway, Scotland",
"Riccarton, Ayrshire, Scotland",
"24 Munches Street, Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"7 Wilton Park, Wilton, Roxburghshire, Scotland",
"",
"",
"",
"Queensberry Street, Dumfries, Dumfries and Galloway, Scotland",
"12 Irish Street, Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"74 Queensberry Street, Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"Murray Street, Annan, Dumfries and Galloway, Scotland",
"Ireland",
"Neilston, Renfrewshire, Scotland",
"Charnwood Maternity Home, Dumfries, Dumfries and Galloway, Scotland",
"35 Munches St, Dumfries, Dumfries and Galloway, Scotland",
"",
"Charnwood Maternity Home, Dumfries, Dumfries and Galloway, Scotland",
"",
"48 Sunderries Road, Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"7 Wilton Park, Wilton, Roxburghshire, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"24 Munches Street, Dumfries, Dumfries and Galloway, Scotland",
"Springholm, Kirkcudbrightshire, Scotland",
"Eaglesham, Renfrewshire, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"Langholm, Dumfries and Galloway, Scotland",
"Charnwood Maternity Home, Dumfries, Dumfries and Galloway, Scotland",
"",
"Riccarton, Ayrshire, Scotland",
"",
"",
"",
"",
"Ireland",
"",
"",
"12 Irish Street, Dumfries, Dumfries and Galloway, Scotland",
"Borthwick, Midlothian, Scotland",
"",
"Nith Place, Dumfries, Dumfries and Galloway, Scotland",
"",
"Clerkhill Cottage Burns Street, Dumfries, Dumfries and Galloway, Scotland",
"Kirkgunzeon, Dumfries and Galloway, Scotland",
"",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"Lochrutton, Kirkcudbrightshire, Scotland",
"Kirkgunzeon, Dumfries and Galloway, Scotland",
"Lochrutton, Kirkcudbrightshire, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"Lochrutton, Kirkcudbrightshire, Scotland",
"Chorlton, Cheshire, England",
"Dumfries, Dumfries and Galloway, Scotland",
"Kirkmahoe, Dumfries and Galloway, Scotland",
"",
"Kirkmahoe, Dumfries and Galloway, Scotland",
"Kirkgunzeon, Dumfries and Galloway, Scotland",
"Lochrutton, Kirkcudbrightshire, Scotland",
"Lochrutton, Kirkcudbrightshire, Scotland",
"Lochrutton, Kirkcudbrightshire, Scotland",
"Kirkmahoe, Dumfries and Galloway, Scotland",
"Annan, Dumfries and Galloway, Scotland",
"Kirkmahoe, Dumfries and Galloway, Scotland",
"Lochrutton, Kirkcudbrightshire, Scotland",
"Kirkgunzeon, Dumfries and Galloway, Scotland",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"Kirkgunzeon, Dumfries and Galloway, Scotland",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"Lochrutton, Kirkcudbrightshire, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"Lochrutton, Kirkcudbrightshire, Scotland",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"",
"Ireland",
"Maidenhead, Berkshire, England",
"Maidenhead, Berkshire, England",
"",
"Maidenhead, Berkshire, England",
"Maidenhead, Berkshire, England",
"",
"Maidenhead, Berkshire, England",
"",
"Rochford, Essex, England",
"",
"",
"",
"Lochrutton, Kirkcudbrightshire, Scotland",
"Lochrutton, Kirkcudbrightshire, Scotland",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"Kirkcudbrightshire, Scotland",
"Lochrutton, Kirkcudbrightshire, Scotland",
"Sanquhar, Dumfries and Galloway, Scotland",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"",
"Lochrutton, Kirkcudbrightshire, Scotland",
"Sowerby Bridge, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"",
"",
"Strachur, Argyle and Bute, Scotland",
"Strachur, Argyle and Bute, Scotland",
"Strachur, Argyle and Bute, Scotland",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Exeter, Devon, England",
"Exeter, Devon, England",
"Exeter, Devon, England",
"North Bovey, Devon, England",
"Exeter, Devon, England",
"Exeter, Devon, England",
"Exeter, Devon, England",
"Exeter, Devon, England",
"Luddenden, West Yorkshire, England",
"Luddenden, West Yorkshire, England",
"Glasgow, Lanarkshire, England",
"Barnet, Hertfordshire, England",
"Worcester, Worcestershire, England",
"Whetstone, Leicestershire, England",
"",
"",
"Stoke upon Trent, Staffordshire, England",
"",
"Warley, West Yorkshire, England",
"",
"Hackney, London, England",
"",
"",
"Lambeth, Greater London, England",
"Hendon, London, England",
"Minterne Magna, Dorset, England",
"",
"",
"Sandhurst, Berkshire, England",
"Crowthorne, Berkshire, England",
"",
"Coldstream, Scottish Borders, Scotland",
"",
"Sydney, Australia",
"",
"",
"Victoria, British Columbia, Canada",
"",
"Paiganton, Devon, England",
"Paiganton, Devon, England",
"Ontario, Canada",
"Sussex, England",
"Midlothian, Scotland",
"",
"Peebles, Peeblesshire, Scotland",
"Peebles, Peeblesshire, Scotland",
"Midlothian, Scotland",
"Midlothian, Scotland",
"Camberwell,London,England",
"Peebles, Peeblesshire, Scotland",
"Islington, London, England",
"91 Ranelagh Road, Pimlico, London, England",
"Carmichael,lanarkshire, Scotland",
"",
"Peebles, Peeblesshire, Scotland",
"Peebles, Peeblesshire, Scotland",
"Peebles, Peeblesshire, Scotland",
"Midlothian, Scotland",
"Midlothian, Scotland",
"Rochford, Essex, England",
"Rochford, Essex, England",
"Rochford, Essex, England",
"Rochford, Essex, England",
"Rochford, Essex, England",
"",
"Rochford, Essex, England",
"",
"Whetstone, Leicestershire, England",
"Blaby, Leicesteshire",
"Whetstone, Leicestershire, England",
"Blaby, Leicesteshire",
"Whetstone, Leicestershire, England",
"Whetstone, Leicestershire, England",
"",
"Sutton, Cambridgeshire, England",
"Sutton, Cambridgeshire, England",
"Bluntisham, Cambridgeshire, England",
"",
"Devon, England",
"Halifax, West Yorkshire, England",
"",
"",
"",
"Exeter, Devon, England",
"Exeter, Devon, England",
"Exeter, Devon, England",
"Exeter, Devon, England",
"",
"",
"Clifton, West Yorkshire, England",
"Frome, Somerset, England",
"Elm, Cambridgeshire, England",
"",
"",
"",
"",
"",
"Islington, London, England",
"Islington, London, England",
"",
"Fulham, Greater London, England",
"",
"",
"",
"",
"",
"",
"Watford",
"Birmingham,West Midlands,England",
"Ontario, Canada",
"",
"Whetstone, Leicestershire, England",
"Whetstone, Leicestershire, England",
"Blaby, Leicesteshire",
"Whetstone, Leicestershire, England",
"Whetstone, Leicestershire, England",
"Whetstone, Leicestershire, England",
"Whetstone, Leicestershire, England",
"Whetstone, Leicestershire, England",
"Whetstone, Leicestershire, England",
"Leicester, Leicestershire, England",
"Leicester, Leicestershire, England",
"Whetstone, Leicestershire, England",
"Leicester, Leicestershire, England",
"Whetstone, Leicestershire, England",
"Whetstone, Leicestershire, England",
"Leicester, Leicestershire, England",
"Whetstone, Leicestershire, England",
"Whetstone, Leicestershire, England",
"Whetstone, Leicestershire, England",
"Whetstone, Leicestershire, England",
"Whetstone, Leicestershire, England",
"Whetstone, Leicestershire, England",
"Whetstone, Leicestershire, England",
"",
"",
"Weymouth, Dorset, England",
"",
"",
"",
"",
"",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Plymouth, Devon, England",
"Crediton, Devon, England",
"",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"",
"Crediton, Devon, England",
"Crediton, Devon, England",
"",
"",
"",
"",
"Frome, Somerset, England",
"Shaftesbury, Dorset, England",
"Shaftesbury, Dorset, England",
"Wincanton, Somerset, England",
"Sturminster Newton, Dorset, England",
"",
"Wincanton, Somerset, England",
"",
"Sturminster Newton, Dorset, England",
"Wincanton, Somerset, England",
"",
"",
"Dorchester, Devon, England",
"",
"Wincanton, Somerset, England",
"",
"St Pancras, London, England",
"",
"Devon, England",
"",
"Morchard Bishop, Devon, England",
"",
"Sampford Courtenay, Devon, England",
"Leicestershire, England",
"Leicestershire, England",
"Blaby, Leicesteshire",
"Wigston, Leicestershire, England",
"Blaby, Leicesteshire",
"Wigston, Leicestershire, England",
"Ince-in-Makerfield, Greater Manchester, England",
"Wigan, Greater Manchester, England",
"Ince-in-Makerfield, Greater Manchester, England",
"Ince-in-Makerfield, Greater Manchester, England",
"",
"Wolstanton, Staffordshire, England",
"Silverdale, Staffordshire, England",
"Wigan, Greater Manchester, England",
"",
"Wolstanton, Staffordshire, England",
"Silverdale, Staffordshire, England",
"Wigan, Greater Manchester, England",
"Cheshire, England",
"Ince-in-Makerfield, Greater Manchester, England",
"",
"Silverdale, Staffordshire, England",
"",
"",
"",
"",
"",
"",
"Exeter, Devon, England",
"",
"",
"Kingsbury, London, England",
"Kingsbury, London, England",
"Wealdstone, Greater London, England",
"Chiswick, Greater London, England",
"Holy Innocents, Kingsbury, Middlesex,England",
"Hendon, London, England",
"Tufnell Park, Greater London, England",
"Chiswick, Greater London, England",
"",
"Wealdstone, Greater London, England",
"Hendon, London, England",
"Wealdstone, Greater London, England",
"Vauxhall, Greater London, England",
"Harrow, England",
"Chiswick, Greater London, England",
"Kingsbury, London, England",
"Lambeth, Greater London, England",
"",
"Wealdstone, Greater London, England",
"Kingsbury, London, England",
"Kingsbury, London, England",
"Chiswick, Greater London, England",
"",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"Kingsbury, London, England",
"Chiswick, Greater London, England",
"Highgate, Greater London, England",
"",
"Ontario, Canada",
"Uxbridge, Greater London, England",
"St Albans, Hertfordshire, England",
"Stepney, London, England",
"Kensington, Greater London, England",
"Wapping, London, England",
"Mansfield, Nottingham, England",
"Wapping, London, England",
"Alston,Cumbria,England",
"Kingsbury, London, England",
"Chiswick, Greater London, England",
"",
"",
"",
"",
"Buckland Brewer, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Buckland Filleigh, Devon England",
"Parkham, Devon, England",
"",
"",
"Buckland Filleigh, Devon England",
"Devon, England",
"Parkham, Devon, England",
"Parkham, Devon, England",
"",
"Crediton, Devon, England",
"Crediton, Devon, England",
"",
"Buckland Filleigh, Devon England",
"Crediton, Devon, England",
"Parkham, Devon, England",
"Winscott, St Giles in the Wood, Devon, England",
"Buckland Filleigh, Devon England",
"Buckland Filleigh, Devon England",
"Parkham, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Buckland Filleigh, Devon England",
"Parkham, Devon, England",
"Buckland Filleigh, Devon England",
"Parkham, Devon, England",
"Buckland Brewer, Devon, England",
"",
"",
"Parkham, Devon, England",
"Parkham, Devon, England",
"Crediton, Devon, England",
"Buckland Filleigh, Devon England",
"Devon, England",
"Parkham, Devon, England",
"Parkham, Devon, England",
"",
"",
"Parkham, Devon, England",
"Crediton, Devon, England",
"Wilkesport, Ontatio, Canada",
"Sowerby Bridge, West Yorkshire, England",
"Harrow, England",
"Harrow, England",
"Pinner, Greater London",
"Harrow, England",
"Harrow, England",
"Harrow, England",
"Hendon, London, England",
"Dorking, Surrey, England",
"Dorking, Surrey, England",
"Dorking, Surrey, England",
"Dorking, Surrey, England",
"Holmwood, Surrey, England",
"Capel, Surrey, England",
"Capel, Surrey, England",
"Capel, Surrey, England",
"Brierley, South Yorkshire, England",
"",
"",
"",
"",
"Southleigh, Devon, England",
"Great Sampford, Essex, England",
"Wivenhoe, Essex, England",
"",
"Cornwall,England",
"Cornwall,England",
"Ireland",
"",
"",
"",
"",
"",
"",
"",
"Bolton, Lancashire, England",
"Devonport, Devon, England",
"",
"",
"",
"",
"Huntingdon, Cambridgeshire, England",
"Huntingdon, Cambridgeshire, England",
"Horley, Surrey, England",
"Horley, Surrey, England",
"Horley, Surrey, England",
"Horley, Surrey, England",
"Horley, Surrey, England",
"Horley, Surrey, England",
"Horley, Surrey, England",
"Nutfield, Surrey, England",
"",
"",
"",
"London, England",
"Rothwell, Northamptonshire, England",
"Fulham, Greater London, England",
"Bletchingley, Surrey, England",
"",
"",
"",
"",
"",
"",
"",
"",
"Marylebone, Greater London, England",
"",
"Hanover Square, Westminster, Greater London, England",
"Hanover Square, Westminster, Greater London, England",
"",
"Sheffield, South Yorkshire, England",
"",
"Whetstone, Leicestershire, England",
"Aberdeen, Scotland",
"Erringden, West Yorkshire, England",
"Crediton, Devon, England",
"Horbury, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Weston Super Mare, Somerset, England",
"Neath, West Glamorgan, Wales",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"Weston Super Mare, Somerset, England",
"Axbridge, Somerset, England",
"Crediton, Devon, England",
"Crediton, Devon, England",
"",
"Honiton, Devon, England",
"Willesden, Greater London, England",
"Reigate, Surrey, England",
"Reigate, Surrey, England",
"Manchester, Greater Manchester, England",
"Exeter, Devon, England",
"Yorkshire, England",
"Cononley, North Yorkshire, England",
"Cononley, North Yorkshire, England",
"Cononley, North Yorkshire, England",
"Cononley, North Yorkshire, England",
"West Yorkshire, England",
"Hebden Bridge, West Yorkshire,England",
"West Yorkshire, England",
"",
"",
"",
"",
"",
"Innerleithen, Peebleshire, Scotland",
"",
"",
"Peebles, Peeblesshire, Scotland",
"Peebles, Peeblesshire, Scotland",
"Peebles, Peeblesshire, Scotland",
"Hatherleigh, Devon, England",
"",
"",
"",
"",
"",
"Bernard Heath, Hertfordshire, England",
"",
"Guilford, Surrey, England",
"Leicestershire, England",
"",
"Halifax, West Yorkshire, England",
"Warley, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Sowerby Bridge, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Islington, London, England",
"",
"",
"Wye, Kent, England",
"",
"",
"Maidenhead, Berkshire, England",
"Maidenhead, Berkshire, England",
"Brentford, London, England",
"Maidenhead, Berkshire, England",
"",
"Maidenhead, Berkshire, England",
"",
"Brentford, London, England",
"Bridekirk, Cumberland, England",
"Papcastle, Cumbria, England",
"Whitehaven, Cumbria, England",
"Keswick, Cumbria, England",
"Bewcastle, Cumbria,England",
"Keswick, Cumberland, England",
"",
"",
"Ireland",
"Keysoe, Bedfordshire, England",
"Peebles, Peeblesshire, Scotland",
"Elsworth, Cambridgeshire, England",
"Orange County, Virginia, USA",
"",
"Osbaston, Leicestershire, England",
"Markfield, Leicestershire, England",
"",
"Fenstanton, Cambridgeshire, England",
"Bluntisham, Cambridgeshire, England",
"",
"",
"Alberta, Canada",
"",
"",
"",
"",
"",
"Hendon, London, England",
"Calgary, Alberta, Canada",
"",
"Exeter, Devon, England",
"",
"Sowerby Bridge, West Yorkshire, England",
"Bagshot, Surrey, England",
"Sowerby Bridge, West Yorkshire, England",
"Skircoat, West Yorkshire, England",
"Halifax, West Yorkshire, England",
"Redhill, Surrey, England",
"Sowerby Bridge, West Yorkshire, England",
"Yorkshire, England",
"Yorkshire, England",
"Horsell, Surrey, England",
"St Mary Magdalen, Bermondsey, Surrey, England",
"Redhill, Surrey, England",
"7 Windsor Avenue, New Maulden, Surrey, England",
"Redhill, Surrey, England",
"Redhill, Surrey, England",
"Wigan, Greater Manchester, England",
"7 Windsor Avenue, New Maulden, Surrey, England",
"",
"Birstall, West Yorkshire, England",
"Yorkshire, England",
"Horley, Surrey, England",
"Horley, Surrey, England",
"Bagshot, Surrey, England",
"Horley, Surrey, England",
"Horley, Surrey, England",
"Bagshot, Surrey, England",
"",
"",
"",
"Exeter, Devon, England",
"Exeter, Devon, England",
"Exeter, Devon, England",
"",
"",
"Ontario, Canada",
"",
"",
"Ontario, Canada",
"",
"",
"",
"Kensington, Greater London, England",
"Clerkenwall, Greater London,England",
"",
"Leicester, Leicestershire, England",
"Blaby, Leicesteshire",
"Leicester, Leicestershire, England",
"Blaby, Leicesteshire",
"Blaby, Leicesteshire",
"Blaby, Leicesteshire",
"Blaby, Leicesteshire",
"Blaby, Leicesteshire",
"Whetstone, Leicestershire, England",
"Whetstone, Leicestershire, England",
"Leicester, Leicestershire, England",
"",
"",
"",
"",
"Middlesex, England",
"",
"Tottenham, London, England",
"Little Paxton, Cambridgeshire, England",
"Great Paxton, Cambrideshire,England",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"Great Paxton, Cambrideshire,England",
"",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"Saint Neots/ St Neots/ St. Neots, Cambridgeshire, England",
"",
"Great Paxton, Cambrideshire,England",
"",
"",
"",
"",
"Ecclesall, South Yorkshire, England",
"",
"Bargoed, Wales",
"",
"",
"St Thomas, Devon, England",
"",
"Libberton, Lanarkshire, Scotland",
"Bluntisham, Cambridgeshire, England",
"Bluntisham, Cambridgeshire, England",
"",
"",
"Lambeth, Greater London, England",
"Lambeth, Greater London, England",
"Brentford, London, England",
"Lewisham, Borough of Lewisham, Greater London, England",
"Stepney, London, England",
"Stepney, London, England",
"Stepney, London, England",
"Wandsworth, Greater London, England",
"Wandsworth, Greater London, England",
"Stepney, London, England",
"",
"Fulham, Greater London, England",
"Stepney, London, England",
"Brentford, London, England",
"Kingston Upon Thames, Greater London, England",
"Dartford, Kent, England",
"Hackney, London, England",
"",
"",
"Whetstone, Leicestershire, England",
"",
"Whetstone, Leicestershire, England",
"Whetstone, Leicestershire, England",
"Whetstone, Leicestershire, England",
"Illinois,USA",
"Devon, England",
"",
"St. Ives, Cambridgeshire, England",
"Bluntisham, Cambridgeshire, England",
"St. Ives, Cambridgeshire, England",
"St. Ives, Cambridgeshire, England",
"Bluntisham, Cambridgeshire, England",
"Lambeth, Greater London, England",
"Warboys, Cambridgeshire, England",
"Pidley Cum Fenton, Cambridgeshire, England",
"Marylebone, Greater London, England",
"",
"",
"",
"",
"",
"7 Windsor Avenue, New Maulden, Surrey, England",
"Warrington, Lancashire, England",
"",
"Great Paxton, Cambrideshire,England",
"",
"Ramsden Bellhouse, Essex, England",
"Ramsden Bellhouse, Essex, England",
"",
"Edmonton, Greater London, England",
"",
"Peebles, Peeblesshire, Scotland",
"",
"",
"Carlisle, Cumbria, England",
"Chesterton, Cambridgeshire, England",
"Merstham, Surrey, England",
"Hanley, Staffordshire, England",
"Merstham, Surrey, England",
"",
"Peebles, Peeblesshire, Scotland",
"Merstham, Surrey, England",
"Merstham, Surrey, England",
"Peebles, Peeblesshire, Scotland",
"Chipstead, Surrey, England",
"Merstham, Surrey, England",
"Merstham, Surrey, England",
"Merstham, Surrey, England",
"Luddenden, West Yorkshire, England",
"Yorkshire, England",
"Luddenden, West Yorkshire, England",
"Warley, West Yorkshire, England",
"Warley, West Yorkshire, England",
"Warley, West Yorkshire, England",
"St John The Baptist Church, Halifax, Yorkshire, England",
"Warley, West Yorkshire, England",
"",
"Dumfries, Dumfries and Galloway, Scotland",
"Groby, Leicestershire, England",
"",
"",
""
]
Dwr.ScriptLoaded('dwr_db_I_birth_place_0.js');
